DB_FILE_NAME = 'main.sqlite'
RATINGS_TABLE_NAME = 'meme_ratings'
RATED_MEME_IDS_NAME = 'rated_meme_ids'
CONFIG_OPTIONS_TABLE_NAME = 'config_options'
INSULTS_TABLE_NAME = 'insults'
BANNED_DOMAINS_TABLE_NAME = 'banned_domains'
